export const enum AuthActionTypes {
  REGISTER_FAIL = "REGISTER_FAIL",
  REGISTER_SUCCESS = "REGISTER_SUCCESS",
  LOGIN_FAIL = "LOGIN_FAIL",
  LOGIN_SUCCESS = "LOGIN_SUCCESS",
  LOGOUT = "LOGOUT",
  SET_MESSAGE = "SET_MESSAGE",
  CLEAR_MESSAGE = "CLEAR_MESSAGE",
}
